"""initial commit

Revision ID: 014291860921
Revises: d1c140ad62c5
Create Date: 2022-02-16 17:03:52.880384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '014291860921'
down_revision = 'd1c140ad62c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pin', sa.Column('user_pin', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pin', 'user', ['user_pin'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pin', type_='foreignkey')
    op.drop_column('pin', 'user_pin')
    # ### end Alembic commands ###
