"""Initial Migration

Revision ID: 2d39aa44219e
Revises: 
Create Date: 2022-02-15 18:40:28.547112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d39aa44219e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_from', sa.Integer(), nullable=True),
    sa.Column('message_to', sa.String(length=255), nullable=True),
    sa.Column('message', sa.String(length=3000), nullable=True),
    sa.Column('received_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_from'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_pin', sa.Integer(), nullable=True),
    sa.Column('chat_pin', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_pin'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pin')
    op.drop_table('chat')
    op.drop_table('user')
    # ### end Alembic commands ###
