"""initial migrate

Revision ID: 6691049f0519
Revises: 
Create Date: 2022-02-16 10:50:13.456208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6691049f0519'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('pass_secure', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_from', sa.Integer(), nullable=True),
    sa.Column('message_to', sa.String(length=255), nullable=True),
    sa.Column('message', sa.String(length=3000), nullable=True),
    sa.Column('received_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_from'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_pin', sa.Integer(), nullable=True),
    sa.Column('chat_pin', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_pin'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pin')
    op.drop_table('chat')
    op.drop_table('users')
    # ### end Alembic commands ###
