"""Initial migration

Revision ID: 8f2437e52c5d
Revises: 
Create Date: 2022-02-16 20:48:32.678485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f2437e52c5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_from', sa.String(length=100), nullable=True),
    sa.Column('message_to', sa.String(length=255), nullable=True),
    sa.Column('message', sa.String(length=3000), nullable=True),
    sa.Column('received_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('added_by', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_pin', sa.Integer(), nullable=True),
    sa.Column('chat_pin', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_pin'], ['registration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pin')
    op.drop_table('registration')
    op.drop_table('contacts')
    op.drop_table('chat')
    # ### end Alembic commands ###
