"""initial commit

Revision ID: af39a8681424
Revises: 014291860921
Create Date: 2022-02-17 06:38:04.102312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af39a8681424'
down_revision = '014291860921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('saved_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contacts', 'user', ['saved_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_column('contacts', 'saved_by')
    # ### end Alembic commands ###
