"""initial commit

Revision ID: d1c140ad62c5
Revises: 1f37e206e88a
Create Date: 2022-02-16 17:03:26.095483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1c140ad62c5'
down_revision = '1f37e206e88a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('message_from', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chat', 'user', ['message_from'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat', type_='foreignkey')
    op.drop_column('chat', 'message_from')
    # ### end Alembic commands ###
